### ISSUE TITLE
Add default search for BrowseViews

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/bread#107]
For the person browse overview we use a special SearchBackendConfig. This is good and should not change.
However, the bread.views.BrowseView actually supports filtering via a URL parameter ("q" by default). This is currently not used anywhere.

We need to add support so that any browse view can have a simple default search. ```BrowseView.get_queryset``` has the filtering via djangoql implemented, this should be reused. We need to implement a configuration parameter so that a default SearchBackendConfig can be used for any view

An example use case would be the report browse view. Right now there is no way to search for the name of a report. After this is implemented, the report view should have a search-bar (via SearchConfigBackend) which allows to search by name. The browse view for reports should only need a small additional parameter to enable that search bar.

Important: This functionality should not use the ```resultcontainerid``` of ```bread.layout.components.search.Search``` but work via URL-queries and page reloads. It might be a bit challenging to implement this so that both ways work.

**Comment by dward2nd** [comment]
Done.

**Comment by dward2nd** [comment]
Done as in this PR #110

**Comment by dward2nd** [comment]
Moved from Test to Development because I got some comments from @saemideluxe to adjust something.

**Comment by dward2nd** [comment]
I have almost completed the default search box for BrowseView. However, I still encounter a problem distinguishing between the general search input box one and one that might appear in other places (like a navigation bar).

**Comment by dward2nd** [comment]
We can technically apply this solution though it might look ugly in practice. Or maybe we should temporarily remove the default value based on the GET queries.

<img width="672" alt="Screen Shot 2022-01-02 at 午後01 55 15" src="https://user-images.githubusercontent.com/49072867/147868627-66c681dd-bf41-4a9e-ae57-2644286c0582.png">

**Comment by saemideluxe** [comment]
Okay for now
