### ISSUE TITLE
How to integrate systeminformation?

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/bread#68]
@frederikbugglin We have a page called "Systeminformation" at the path /systeminformation . It is currently not integrated into the menu system because it is mostly usefull for us to review the system configuration, check if we are on the newest version etc. I think we will expand that page in the future a bit, similar to "System Status" or "Health Check" pages of other systems.

Do you think we should integrate that page as a link somewhere or leave it as is for now? I is not too relevant for end-users I think.

**Comment by saemideluxe** [comment]
Also: We might want some information about background-jobs, in order to detect problems e.g. with synchronization.

**Comment by frederikbugglin** [comment]
Example:
<img width="714" alt="Bildschirmfoto 2021-09-15 um 17 03 50" src="https://user-images.githubusercontent.com/74606126/133570094-e7e63206-6ba6-48f8-a412-eb5b1af4c89f.png">

**Comment by saemideluxe** [comment]
Okay, we have now a basic version of this inside the basxconnect project. I think we will move the according views inside bread.

**Comment by saemideluxe** [comment]
Closing in favor of #91
