### ISSUE TITLE
Add example code for usage of Datatable

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/bread#89]
The docstring for the Datatable component is a bit too technical, especially when using it for the first time. We should add some example code on how to display a simple table from a simple datastructure like

```python
headers = ["Country", "Continent", "Population"]
rows = [
    ["Switzerland", "Europe", 8_500_00],
    ["Germany", "Europe", 83_000_00],
    ["Thailand", "Asia", 70_000_00],
]
```
or something similar.

**Comment by dward2nd** [comment]
I added a simple example and will make a pull request later.

**Comment by saemideluxe** [comment]
Okay, thanks.. In the future please make the PR first and linke the issue inside the PR description (like this: #89 ), before you close the issue. That way we will know which PR will solve the issue.

**Comment by saemideluxe** [comment]
(FYI you can link an issue by just typing ```#89```)

**Comment by dward2nd** [comment]
This pull request #95 would solve the issue. Thank you.
