### ISSUE TITLE
Add a testcase which checks all URLs that they are not accessible for non-logged in users

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/bread#90]
Reasoning: Because almost all pages/views in bread projects are no public, we want to make sure that there are no pages which are accidentally accessible by anonymous users.

Concep:
1. Get a list of all urlpatterns of the current django configuration
2. For each URL:
   - Try to generate a valid URL (sometimes a stub value needs to be inserted into the URL
   - Access the URL via the test client (see https://docs.djangoproject.com/en/dev/topics/testing/tools/)
   - Make sure the response is HTTP FORBIDDEN (except for login and passwort-reset views)

There is already an existing test-directory in the project.

**Comment by saemideluxe** [comment]
- I think this will take some time to implement.
- The implementation should happen inside bread
- In order to test it with many URLs the test should be run from the basxconnect_demo project. (with ```./manage.py test bread```)

**Comment by dward2nd** [comment]
The BrowseView has been made a pull request in #98 . The functionality may be added later.

**Comment by dward2nd** [comment]
Sorry, I closed the wrong one.

**Comment by dward2nd** [comment]
The current progress of this issue can be seen in the `feature/administrationmenu` repo. Currently, the method to check the visibility isn't guaranteed to be the optimal one so far. The TestCase was made to check a selected amount of views. Those urlpatterns outside bread (especially basxconnect) are currently ignored.

**Comment by dward2nd** [comment]
Done in #98
