### ISSUE TITLE
Add menu item "Background jobs" to menu group "Administration"

### ISSUE THREAD

**Issue by saemideluxe** [basxsoftwareassociation/bread#92]
We use Celery (https://docs.celeryproject.org/) in some projects. This allows us to run automated background jobs. We need a view where we can see results of background jobs. My suggestion is to register a new browse-view for ```TaskResult``` (see https://github.com/celery/django-celery-results/blob/master/django_celery_results/models.py) and then add a menu item to link to that view. A similar view exists already in the django-admin backend.

**Comment by saemideluxe** [comment]
Info: celery and django-celery-results are already installed as part of any bread project.

**Comment by dward2nd** [comment]
The BrowseView has been made a pull request in #98 . The additional functionalities may be added later.
